### PR TITLE
Fix for building UE5 Editor on Linux

### PR DESCRIPTION
**Pull request by nemui**
On Linux InInt64Data is `long long`, while `FHoudiniApi::SetAttributeInt64Data()` expects `long`.

My C++ is ultra-rusty, so suggestions on how to do this better are welcome!
Tested locally on a Linux CI agent.

### CODE REVIEW

**Comment by nemui** [comment]
Hmm, perhaps `reinterpret_cast()` will work as well, lemme check.

**Comment by nemui** [comment]
Alternatively we can do just `(HAPI_Int64 *)InInt64Data`, looks like?

**Comment by moppius** [comment]
This was the fix from SideEffects last time I saw this issue:
https://github.com/sideeffects/HoudiniEngineForUnreal-v2/issues/135

But I would just go with whatever is simplest.

**Comment by nemui** [comment]
> This was the fix from SideEffects last time I saw this issue: [sideeffects/HoudiniEngineForUnreal-v2#135](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/issues/135)
> 
> But I would just go with whatever is simplest.

I guess I will go with the current version then, since it's closer to their fix.

Do I just merge this in then? How will it make it into our p4 codebase?

**Review by moppius — APPROVED** [review]
Yes, just merge this PR and I will roll it into the UE5 branch manually.
FYI, [the docs for our plugin process are here on Notion](https://www.notion.so/embarkstudios/HOWTO-Add-an-Unreal-Plugin-to-our-Games-011fd39c1ad34d24b681d57e4c485560).

**Comment by nemui** [comment]
> Yes, just merge this PR and I will roll it into the UE5 branch manually. FYI, [the docs for our plugin process are here on Notion](https://www.notion.so/embarkstudios/HOWTO-Add-an-Unreal-Plugin-to-our-Games-011fd39c1ad34d24b681d57e4c485560).

Thanks! Let me know so that I can retry building Linux Editor in CI 💪🏼

**Pull request merged**
